// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsiqzfrasqcddbozvxqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzaXF6ZnJhc3FjZGRib3p2eHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MTM2NDIsImV4cCI6MjA1NTE4OTY0Mn0.AWMjFZZEhdQbB966EjYo2HOXHcuIG1Ym3ktUFSoY1Z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);